server:
  port: 10080
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    callSettersOnNulls: true
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: Tepia@123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.110.66.174/zhhj?useSSL=true&allowMultiQueries=true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
logging:
  level:
    org:
      springframework:
        security: DEBUG
security:
  scope: all
  clientId: tepia
  secret: tepia
  url: http://localhost:10080/oauth/token
